### ISSUE TITLE
Personal links left in config files.

### ISSUE THREAD

**Issue by khobiziilyes** [EliTheSurfer/EliVim-VSCode#7]
Hello, first of all thanks for sharing this great tweak with us!
I've been impressed by how far you could extend the editor, and while I was trying to understand all of the different extensions I found out some of the config that I don't think you were attending to share with us, which you may find here:
https://github.com/EliTheSurfer/EliVim-VSCode/blob/828456e7ad943e26e273d1fb58d1e41d4d43d7b6/settings.json#L97
https://github.com/EliTheSurfer/EliVim-VSCode/blob/828456e7ad943e26e273d1fb58d1e41d4d43d7b6/settings.json#L347

**Comment by EliTheSurfer** [comment]
you are absolutely right sir, thanks @khobiziilyes , i am removing it right now
